### ISSUE TITLE
第11章: 少了斷句, 讀起來不順

### ISSUE THREAD

**Issue by joanlin2** [xdite/blitz-product#1]
为什么不是 9-10 分的顾客？ --- 因为他们已经愿意推荐你的服务 为什么不是 6 分以下的顾客？ --- 会打到 6 分以下的顾客，通常对你已经很生气（因为各式理由）。短时间你也没办法让他满意。

<<<看原code才知有換行, 但是呈現上全擠起一起了>>>

建議這樣改==>
「为什么不是 9-10 分的顾客？」 因为他们已经愿意推荐你的服务。 「为什么不是 6 分以下的顾客？」 那些会打到 6 分以下的顾客，通常对你已经很生气（因为各式理由）。短时间你也没办法让他满意。

**Comment by xdite** [comment]
done
