### ISSUE TITLE
小建議: 00.md

### ISSUE THREAD

**Issue by ryanjdpeng** [xdite/blitz-product#10]
在风口上误打误撞上却把公司做起来了，
=>在风口上误打误撞的却把公司做起来了，
or  在风口上误打误撞中，却把公司做起来了，

Fake it unit make it
=> fake it _till you_ make it

当时让我深深让我著迷
=>当时_就让我深深_著迷
or 当时_就深深让我_著迷

我人生的愿望就变成了希望未来成为一个软件创业者
=> 我人生的愿望就变成了：未来成为一个软件创业者

从程序员菜鸟自我锻炼到_到_程序员行业的大神
=>从程序员菜鸟自我锻炼到程序员行业的大神

站上产生的年 GMV 超过100亿人民币
=> 站上年 GMV (Gross Merchandise Volume,網站成交金額) 超过100亿人民币

不仅能在风口里面极短的时间开发出产品顺利切入，
=> 不仅能在风口里面_，用_极短的时间开发出产品顺利切入，

我钻研不同的方法论以克服看似不可能的问题。
=>我钻研不同的方法论，以克服看似不可能的问题。

謝謝分享

**Comment by xdite** [comment]
fixed
