### ISSUE TITLE
小建議: 01.md

### ISSUE THREAD

**Issue by ryanjdpeng** [xdite/blitz-product#11]
但是我们真确做到了
=> 但是我们真确地做到了
or 但是我们真真确确地做到了

与此同时中国关停了虚拟币相关事业
=> 与此同时，中国关停了虚拟币相关事业

因为当中国，虽然不禁止个人持有比特币，
=> 因为当時中国政府虽然不禁止个人持有比特币，

在上面遇到欺诈黑钱的情况也比比皆是。
=> 在上面遇到欺诈黑钱的情况，也比比皆是。

于是，于是我灵机一动，
=> _ _于是我灵机一动，

时中国币圈大家都在抱怨虚拟币交易不安全。
=> 當时中国币圈大家都在抱怨虚拟币交易不安全。

我们靠著内部独门的用户体验框架，应是领先对手一大截。
=>我们靠著内部独门的用户体验框架，硬是领先对手一大截。

OTCBTC 从决定项目立项，到实际的执行的上线
=> OTCBTC 从决定项目立项，到实际的执行、上线

但是针对刚需进行创业好像也不一定会成功
=>但是针对刚需进行创业，好像也不一定会成功

一旦一样题目火了
=>一旦一個項目做得火了

 但是市场去不买单。
=>但是市场_卻_不买单。

而这时候自己的团队却还在被奇怪的相依性或性能问题甚至是沟通问题卡住
=> 而这时候自己的团队却还在被奇怪的相依性或性能问题、甚至是沟通问题卡住

活生生错过风口，被使用者夺占市场
=> 活生生错过风口，被競爭者夺占市场

我们会在这本书里面 Cover 以下的主题：
=> 我们会在这本书里面 論述到以下的主题：
or 我们会在这本书里面 包含以下的主题：
or 你就是要用 cover

创业者的挑战。不仅止于前期的执行冲刺，后期的持续领先
=> 创业者的挑战。不仅止于前期的执行冲刺；后期的持续领先

营业额开始日破两百万营业额
=> 营业额开始單日破两百万营业额

收尾上线，预先迭代体验，取得领先
=> 预先迭代体验==> 也許我自己的問題，看到後面會看懂

好棒的故事開頭，心驚膽跳、也引人入勝。創業 就是要直抵獲利核心。

**Comment by ryanjdpeng** [comment]
兩章的尾巴 都帶到了四個重點，有點重複

但是第三項，似乎有點不一樣?!

**Comment by xdite** [comment]
fixed
