### ISSUE TITLE
第01章 - 闪电式开发 （文字措辞）

### ISSUE THREAD

**Issue by lijinjf19800404** [xdite/blitz-product#12]
指的是"在风口上做出正确的创业题目，并且顺利的产出项目并取得高增长" 这个圣杯。==》
指的是"在风口上做出正确的创业题目，并且顺利地产出项目并取得高增长"

**Comment by lijinjf19800404** [comment]
我的同事，是之前跟我一起做网路教育平台的同一批人。 ==》
我的同事，是之前跟我一起做网络教育平台的同一批人。

**Comment by lijinjf19800404** [comment]
公司关了。于是只好集体去日本员工旅行，寻找人生以及事业新的方向。==》
公司关停，于是全体日本旅行，寻找人生以及事业新的方向。

**Comment by lijinjf19800404** [comment]
2017 年 5 月，世界上的虚拟币的集体暴涨，让我们公司绝大多数同事，个人的虚拟币投资，人人都收获颇丰，就算没有人人财务自由，但也从此小有积累。

但是，九月份的虚拟币事业关停，却让我们发愁。 ==》

2017 年，区块链的牛市行情让公司绝大多数同事收获颇丰，但，九月份的一道禁令，却让我们发愁。

**Comment by lijinjf19800404** [comment]
因为当中国，虽然不禁止个人持有比特币，但却关停了所有收受法币储值出金的交易所。换句话说：我们大家很有钱，但也穷到都只剩下币。 ==》

大陆虽不禁止个人持有比特币，但关停所有虚拟货币交易所，这意味着：我们有钱，但也都是纸面的虚拟币，无法换法币。

**Comment by xdite** [comment]
fix
