### ISSUE TITLE
00: 建議

### ISSUE THREAD

**Issue by joanlin2** [xdite/blitz-product#2]
- 我负责经营的网站流量也很高。一天可以达到 100 万 PV 以上。在台湾当时可以到达 Alexa 前 50 名。
=>建議補充說明 PV / Alexa 的意思

- YC 投资的公司，都具备强大的 Traction
=> 這句是指吸睛嗎?

- 并且在短短时间在风口上迅速跌，增长速度前所未见
=> 并且在短短时间在风口上迅速**迭代**，增长速度前所未见

**Comment by xdite** [comment]
修正迭代
