### ISSUE TITLE
11.md 錯字訂正或感覺多字

### ISSUE THREAD

**Issue by kiloking** [xdite/blitz-product#4]
但是如果你在最草版本（也就是刚上线）的状泰，就已经曝光给 30万人使用
-> 但是如果你在最草版本（也就是刚上线）的状态，就已经曝光给 30万人使用

总不可能你自己都没用过别人，就盲目推给别人吧。
-> 总不可能你自己都没用过，就盲目推给别人吧。

背后的目的就是不断在优化以及打造背后的增长引擎。
->  背后的目的就是不断在优化以及打造增长引擎。
or ->目的就是不断的优化以及打造背后的增长引擎。

**Comment by xdite** [comment]
done
