### ISSUE TITLE
13.md的錯別字

### ISSUE THREAD

**Issue by iamvista** [xdite/blitz-product#9]
在这一章。我要谈谈创业题目的挑选。 --> 在這一章，

我一直很怕我的这本心法书，给读者一个错觉。就是，无论所有题目，都可以用这一本书当中提到的方法，闪电式开发，然后迅速培育出一支独角兽。 --> 我一直很怕我的这本心法书，给读者一个错觉──就是无论所有题目，都可以用这一本书当中提到的方法「闪电式开发」，然后迅速培育出一支独角兽。

事实上，我这套方法。有失败的例子吗？ --> 事实上，我这套方法有過失败的例子吗？

Youtube --> YouTube

iphone --> iPhone

Airbnb 利用 Craglist 的例子 --> Craigslist

Linkedin 利用使用者的 Outlook --> LinkedIn

「创业就是要细分垄断」一书里面还提到， --> 《创业就是要细分垄断》一书里面还提到，

这三个特征，贯串了我们全书： --> 貫穿

**Comment by xdite** [comment]
fixed
